// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
)

type Product struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	RegularPrice int32          `json:"regular_price"`
	SalePrice    int32          `json:"sale_price"`
	InStock      bool           `json:"in_stock"`
	IsPublish    bool           `json:"is_publish"`
	CategoryID   int32          `json:"category_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type ProductCategory struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	IsPublish   bool           `json:"is_publish"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
