// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testProductCategories(t *testing.T) {
	t.Parallel()

	query := ProductCategories()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testProductCategoriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductCategoriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ProductCategories().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductCategoriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ProductCategorySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductCategoriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ProductCategoryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ProductCategory exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ProductCategoryExists to return true, but got false.")
	}
}

func testProductCategoriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	productCategoryFound, err := FindProductCategory(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if productCategoryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testProductCategoriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ProductCategories().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testProductCategoriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ProductCategories().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testProductCategoriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	productCategoryOne := &ProductCategory{}
	productCategoryTwo := &ProductCategory{}
	if err = randomize.Struct(seed, productCategoryOne, productCategoryDBTypes, false, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, productCategoryTwo, productCategoryDBTypes, false, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = productCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = productCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ProductCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testProductCategoriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	productCategoryOne := &ProductCategory{}
	productCategoryTwo := &ProductCategory{}
	if err = randomize.Struct(seed, productCategoryOne, productCategoryDBTypes, false, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, productCategoryTwo, productCategoryDBTypes, false, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = productCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = productCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func productCategoryBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductCategory) error {
	*o = ProductCategory{}
	return nil
}

func productCategoryAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductCategory) error {
	*o = ProductCategory{}
	return nil
}

func productCategoryAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ProductCategory) error {
	*o = ProductCategory{}
	return nil
}

func productCategoryBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ProductCategory) error {
	*o = ProductCategory{}
	return nil
}

func productCategoryAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ProductCategory) error {
	*o = ProductCategory{}
	return nil
}

func productCategoryBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ProductCategory) error {
	*o = ProductCategory{}
	return nil
}

func productCategoryAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ProductCategory) error {
	*o = ProductCategory{}
	return nil
}

func productCategoryBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductCategory) error {
	*o = ProductCategory{}
	return nil
}

func productCategoryAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductCategory) error {
	*o = ProductCategory{}
	return nil
}

func testProductCategoriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ProductCategory{}
	o := &ProductCategory{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, productCategoryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ProductCategory object: %s", err)
	}

	AddProductCategoryHook(boil.BeforeInsertHook, productCategoryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	productCategoryBeforeInsertHooks = []ProductCategoryHook{}

	AddProductCategoryHook(boil.AfterInsertHook, productCategoryAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	productCategoryAfterInsertHooks = []ProductCategoryHook{}

	AddProductCategoryHook(boil.AfterSelectHook, productCategoryAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	productCategoryAfterSelectHooks = []ProductCategoryHook{}

	AddProductCategoryHook(boil.BeforeUpdateHook, productCategoryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	productCategoryBeforeUpdateHooks = []ProductCategoryHook{}

	AddProductCategoryHook(boil.AfterUpdateHook, productCategoryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	productCategoryAfterUpdateHooks = []ProductCategoryHook{}

	AddProductCategoryHook(boil.BeforeDeleteHook, productCategoryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	productCategoryBeforeDeleteHooks = []ProductCategoryHook{}

	AddProductCategoryHook(boil.AfterDeleteHook, productCategoryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	productCategoryAfterDeleteHooks = []ProductCategoryHook{}

	AddProductCategoryHook(boil.BeforeUpsertHook, productCategoryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	productCategoryBeforeUpsertHooks = []ProductCategoryHook{}

	AddProductCategoryHook(boil.AfterUpsertHook, productCategoryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	productCategoryAfterUpsertHooks = []ProductCategoryHook{}
}

func testProductCategoriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProductCategoriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(productCategoryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProductCategoryToManyCategoryProducts(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ProductCategory
	var b, c Product

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, productDBTypes, false, productColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, productDBTypes, false, productColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.CategoryID = a.ID
	c.CategoryID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.CategoryProducts().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.CategoryID == b.CategoryID {
			bFound = true
		}
		if v.CategoryID == c.CategoryID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := ProductCategorySlice{&a}
	if err = a.L.LoadCategoryProducts(ctx, tx, false, (*[]*ProductCategory)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CategoryProducts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.CategoryProducts = nil
	if err = a.L.LoadCategoryProducts(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CategoryProducts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testProductCategoryToManyAddOpCategoryProducts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ProductCategory
	var b, c, d, e Product

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, productCategoryDBTypes, false, strmangle.SetComplement(productCategoryPrimaryKeyColumns, productCategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Product{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Product{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCategoryProducts(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.CategoryID {
			t.Error("foreign key was wrong value", a.ID, first.CategoryID)
		}
		if a.ID != second.CategoryID {
			t.Error("foreign key was wrong value", a.ID, second.CategoryID)
		}

		if first.R.Category != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Category != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.CategoryProducts[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.CategoryProducts[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.CategoryProducts().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testProductCategoriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testProductCategoriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ProductCategorySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testProductCategoriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ProductCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	productCategoryDBTypes = map[string]string{`ID`: `int`, `Name`: `varchar`, `Slug`: `varchar`, `Description`: `varchar`, `IsPublish`: `tinyint`, `CreatedAt`: `timestamp`, `UpdatedAt`: `timestamp`}
	_                      = bytes.MinRead
)

func testProductCategoriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(productCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(productCategoryAllColumns) == len(productCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testProductCategoriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(productCategoryAllColumns) == len(productCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ProductCategory{}
	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, productCategoryDBTypes, true, productCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(productCategoryAllColumns, productCategoryPrimaryKeyColumns) {
		fields = productCategoryAllColumns
	} else {
		fields = strmangle.SetComplement(
			productCategoryAllColumns,
			productCategoryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ProductCategorySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testProductCategoriesUpsert(t *testing.T) {
	t.Parallel()

	if len(productCategoryAllColumns) == len(productCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLProductCategoryUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ProductCategory{}
	if err = randomize.Struct(seed, &o, productCategoryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ProductCategory: %s", err)
	}

	count, err := ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, productCategoryDBTypes, false, productCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ProductCategory struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ProductCategory: %s", err)
	}

	count, err = ProductCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
